  restart: unless-stopped
  image: do_cron_image
  volumes:
    - /var/log/supervisor/:/var/log/supervisor/
    - /root/ops_scripts:/root/ops_scripts
    - /sys/fs/cgroup:/sys/fs/cgroup
  ports:
    - "9900:9900"
  environment:
